In [1]:
import torch

# Example tensor of maximum probabilities
max_p = torch.tensor([0.1, 0.7, 0.4, 0.95])

# Example tensor of indices from torch.max (p_hat)
p_hat = torch.tensor([0, 2, 1, 3])

# Custom thresholds for each index that p_hat can take
thresholds = torch.tensor([0.5, 0.6, 0.9, 0.8])

# Gather the corresponding thresholds for each index in p_hat
selected_thresholds = thresholds[p_hat]

# Calculate the select_mask by comparing max_p with the selected thresholds
select_mask = max_p.ge(selected_thresholds)

print(f"max_p: {max_p}")
print(f"p_hat: {p_hat}")
print(f"Selected thresholds: {selected_thresholds}")
print(f"select_mask: {select_mask}")

/home/lipeng/anaconda3/envs/torch1.12/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


max_p: tensor([0.1000, 0.7000, 0.4000, 0.9500])
p_hat: tensor([0, 2, 1, 3])
Selected thresholds: tensor([0.5000, 0.9000, 0.6000, 0.8000])
select_mask: tensor([False, False, False,  True])


In [2]:
tensor = torch.full((10,), 0.95)

print(tensor)

tensor([0.9500, 0.9500, 0.9500, 0.9500, 0.9500, 0.9500, 0.9500, 0.9500, 0.9500,
        0.9500])


In [3]:
tensor[2] = 0.2

In [4]:
tensor

tensor([0.9500, 0.9500, 0.2000, 0.9500, 0.9500, 0.9500, 0.9500, 0.9500, 0.9500,
        0.9500])

In [1]:
class MyClass:
    def __init__(self, value):
        self.instance_variable = value

def modify_object(obj):
    obj.instance_variable = "Modified"

# Create an instance of MyClass
a = MyClass("Original")

# Pass the object to the function
modify_object(a)

# The instance variable of 'a' has been modified by the function
print(a.instance_variable)  # Output: Modified

Modified


In [2]:
def modify_object(obj):
    obj.instance_variable = "hhh"

In [3]:
modify_object(a)

In [4]:
a.instance_variable

'hhh'

In [14]:
def getrcps(filename):
    #filename = '/data/lipeng/ABC/txt/cf100_0602t1.txt'
    rc = []
    ps = []
    with open(filename, 'r') as file:
        lines = file.readlines()
        i = 0
        while i < len(lines):
                if lines[i].startswith('Class-wise Metrics (Recall and Precision)'):
                    # Process the next 100 lines to get class index and recall value for the current epoch
                    epoch_info = []
                    recalls = []
                    precisions = []
                    for j in range(i + 1, i + 101):
                        
                        recall, precision = lines[j].split('Recall: ')[1].split(' Precision: ')[0], lines[j].split('Precision: ')[1]
                        recalls.append(recall)
                        precisions.append(precision)
                        #print('class_line',class_line)
                    
                    assert len(recalls) == 100
                    assert len(precisions) == 100
                        
                    rc.append(recalls)
                    ps.append(precisions)
                    
                    #recall_smallest_20.append(sorted_indexes[:20])
                    i += 100  # Move to the next epoch
                else:
                    i += 1
    return rc,ps


In [15]:
f1 = '/data/lipeng/ABC/txt/cf100_0602t1.txt'
f2 = '/data/lipeng/ABC/txt/cf100_0602t2.txt'
f3 = '/data/lipeng/ABC/txt/cf100_0602t3.txt'
f4 = '/data/lipeng/ABC/txt/cf100_0602t4.txt'
f5 = '/data/lipeng/ABC/txt/cf100_0602t5.txt'
f6 = '/data/lipeng/ABC/txt/cf100_0602t6.txt'
f7 = '/data/lipeng/ABC/txt/cf100_0602t7.txt'
f8 = '/data/lipeng/ABC/txt/cf100_0602t8.txt'

In [16]:
rc1,ps1 = getrcps(f1)
rc2,ps2 = getrcps(f2)
rc3,ps3 = getrcps(f3)
rc4,ps4 = getrcps(f4)
rc5,ps5 = getrcps(f5)
rc6,ps6 = getrcps(f6)
rc7,ps7 = getrcps(f7)
rc8,ps8 = getrcps(f8)

In [28]:
l1 = rc1[-5:]
l2 = rc2[-5:]
l3 = rc3[-5:]
l4 = rc4[-5:]
l5 = rc5[-5:]
l6 = rc6[-5:]
l7 = rc7[-5:]
l8 = rc8[-5:]

l1 = [[float(element) for element in sublist] for sublist in l1]
l2 = [[float(element) for element in sublist] for sublist in l2]
l3 = [[float(element) for element in sublist] for sublist in l3]
l4 = [[float(element) for element in sublist] for sublist in l4]
l5 = [[float(element) for element in sublist] for sublist in l5]
l6 = [[float(element) for element in sublist] for sublist in l6]
l7 = [[float(element) for element in sublist] for sublist in l7]
l8 = [[float(element) for element in sublist] for sublist in l8]


In [30]:
s1 = [sum(column) for column in zip(*l1)]
m1 = [sum_value / len(l1) for sum_value in s1]

s2 = [sum(column) for column in zip(*l2)]
m2 = [sum_value / len(l2) for sum_value in s2]

s3 = [sum(column) for column in zip(*l3)]
m3 = [sum_value / len(l3) for sum_value in s3]

s4 = [sum(column) for column in zip(*l4)]
m4 = [sum_value / len(l4) for sum_value in s4]

s5 = [sum(column) for column in zip(*l5)]
m5 = [sum_value / len(l5) for sum_value in s5]

s6 = [sum(column) for column in zip(*l6)]
m6 = [sum_value / len(l6) for sum_value in s6]

s7 = [sum(column) for column in zip(*l7)]
m7 = [sum_value / len(l7) for sum_value in s7]

s8 = [sum(column) for column in zip(*l8)]
m8 = [sum_value / len(l8) for sum_value in s8]

In [44]:
def rete(data):
    indexed_values = list(enumerate(data))

    # Sort the pairs by value
    sorted_indexed_values = sorted(indexed_values, key=lambda x: x[1])

    # Extract the sorted indices
    sorted_indices = [(index,round(value,3)) for index, value in sorted_indexed_values]
    return sorted_indices

In [45]:
sm1 = rete(m1)
sm2 = rete(m2)
sm3 = rete(m3)
sm4 = rete(m4)
sm5 = rete(m5)
sm6 = rete(m6)
sm7 = rete(m7)
sm8 = rete(m8)

In [46]:
print(sm1[:10])
print(sm2[:10])
print(sm3[:10])
print(sm4[:10])
print(sm5[:10])
print(sm6[:10])
print(sm7[:10])
print(sm8[:10])

[(80, 0.074), (98, 0.098), (92, 0.13), (72, 0.134), (55, 0.176), (64, 0.198), (93, 0.2), (83, 0.21), (65, 0.22), (74, 0.226)]
[(80, 0.072), (98, 0.122), (72, 0.13), (92, 0.13), (93, 0.188), (64, 0.228), (83, 0.23), (55, 0.248), (65, 0.258), (73, 0.26)]
[(98, 0.054), (92, 0.076), (80, 0.106), (72, 0.128), (55, 0.212), (93, 0.218), (74, 0.222), (64, 0.23), (65, 0.236), (83, 0.25)]
[(98, 0.054), (80, 0.142), (92, 0.168), (72, 0.186), (93, 0.208), (65, 0.214), (55, 0.222), (50, 0.29), (64, 0.298), (73, 0.306)]
[(92, 0.102), (98, 0.126), (72, 0.128), (80, 0.152), (55, 0.192), (64, 0.228), (93, 0.228), (65, 0.242), (73, 0.278), (50, 0.3)]
[(98, 0.072), (92, 0.122), (80, 0.138), (72, 0.146), (74, 0.194), (55, 0.202), (93, 0.208), (64, 0.262), (84, 0.28), (83, 0.29)]
[(98, 0.084), (92, 0.112), (80, 0.126), (72, 0.206), (55, 0.224), (93, 0.252), (64, 0.284), (84, 0.302), (50, 0.316), (74, 0.322)]
[(98, 0.134), (80, 0.146), (72, 0.154), (92, 0.19), (64, 0.202), (55, 0.22), (65, 0.222), (93, 0.23

In [22]:
l1 = [[float(element) for element in sublist] for sublist in l1]
l2 = [[float(element) for element in sublist] for sublist in l2]
l3 = [[float(element) for element in sublist] for sublist in l3]
l4 = [[float(element) for element in sublist] for sublist in l4]
l5 = [[float(element) for element in sublist] for sublist in l5]
l6 = [[float(element) for element in sublist] for sublist in l6]
l7 = [[float(element) for element in sublist] for sublist in l7]
l8 = [[float(element) for element in sublist] for sublist in l8]

In [23]:
l1

[[0.91,
  0.84,
  0.6,
  0.55,
  0.64,
  0.88,
  0.81,
  0.66,
  0.9,
  0.87,
  0.5,
  0.49,
  0.82,
  0.67,
  0.66,
  0.79,
  0.71,
  0.87,
  0.57,
  0.54,
  0.9,
  0.84,
  0.76,
  0.82,
  0.77,
  0.47,
  0.55,
  0.67,
  0.8,
  0.66,
  0.68,
  0.64,
  0.71,
  0.67,
  0.72,
  0.44,
  0.72,
  0.7,
  0.58,
  0.87,
  0.42,
  0.86,
  0.75,
  0.74,
  0.32,
  0.39,
  0.31,
  0.62,
  0.86,
  0.89,
  0.29,
  0.59,
  0.75,
  0.83,
  0.77,
  0.19,
  0.86,
  0.56,
  0.8,
  0.39,
  0.81,
  0.52,
  0.59,
  0.57,
  0.2,
  0.22,
  0.53,
  0.35,
  0.9,
  0.74,
  0.64,
  0.62,
  0.14,
  0.29,
  0.21,
  0.7,
  0.8,
  0.36,
  0.36,
  0.61,
  0.09,
  0.49,
  0.82,
  0.23,
  0.31,
  0.6,
  0.5,
  0.4,
  0.55,
  0.44,
  0.37,
  0.65,
  0.14,
  0.18,
  0.89,
  0.49,
  0.37,
  0.41,
  0.08,
  0.44],
 [0.92,
  0.84,
  0.62,
  0.54,
  0.6,
  0.87,
  0.83,
  0.71,
  0.88,
  0.87,
  0.45,
  0.51,
  0.8,
  0.63,
  0.65,
  0.79,
  0.73,
  0.88,
  0.58,
  0.6,
  0.9,
  0.84,
  0.73,
  0.83,
  0.77,
  0.46,
  0.54,
 

In [24]:
print(l1[0][-1],l1[1][-1],l1[2][-1],l1[3][-1],l1[4][-1],(l1[0][-1]+l1[1][-1]+l1[2][-1]+l1[3][-1]+l1[4][-1])/5)

0.44 0.46 0.45 0.44 0.47 0.45199999999999996


In [26]:
sums = [sum(column) for column in zip(*l1)]

# Calculate the mean of each dimension by dividing the sum by the number of elements
means = [sum_value / len(l1) for sum_value in sums]

In [27]:
means[-1]

0.45199999999999996

In [47]:
import numpy as np

# Example array
overlap_avg_upart = np.array([10, 20, 30, 40, 50])

# Sorting and getting indices of the biggest values
asc_indices2 = np.argsort(overlap_avg_upart)
desc_indices2 = asc_indices2[::-1]
ret = desc_indices2[:3]

print('Indices of the biggest values:', ret)

Indices of the biggest values: [4 3 2]


In [48]:
import statistics
import torch

dict_from_pairs = {
    'item1': torch.tensor(1.0),
    'item2': torch.tensor(5.0),
    'item3': torch.tensor(8.0)
}

# Convert tensor values to a list of numbers for statistics.mean()
mean_stats = statistics.mean([float(value) for value in dict_from_pairs.values()])
print('Mean using statistics.mean():', mean_stats)

# Calculate the mean using torch.mean()
mean_torch = torch.mean(torch.stack(list(dict_from_pairs.values())), dim=0)
print('Mean using torch.mean():', mean_torch.item())

Mean using statistics.mean(): 4.666666666666667
Mean using torch.mean(): 4.666666507720947


/home/lipeng/anaconda3/envs/torch1.12/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [10]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class SupConLoss3(nn.Module):  #supconloss3对所有样本都有closs但对w类额外加一项  实际上是w类一项 + 非w类一项

    def __init__(self, temperature=0.5,distance=0.5, scale_by_temperature=True):
        super(SupConLoss3, self).__init__()
        self.temperature = temperature
        self.distance = distance
        self.scale_by_temperature = scale_by_temperature

    def forward(self, tmask,worstk,features1, features2,labels1 = None ,labels2 = None, mask=None):# x, u, labelx, labelu
       
        device = (torch.device('cuda'))
        print('features1\n',features1)
        print('features2\n',features2)
        features1 = F.normalize(features1, p=2, dim=1)
        features2 = F.normalize(features2, p=2, dim=1)
        print('features1\n',features1)
        print('features2\n',features2)
        batch_size = features1.shape[0]
        batch_size2 = features2.shape[0]
        # 关于labels参数
        #if labels is not None and mask is not None:  # labels和mask不能同时定义值，因为如果有label，那么mask是需要根据Label得到的
        #    raise ValueError('Cannot define both `labels` and `mask`') 
        #print('labels1[0]',labels1[0])
        num_class = len(labels1[0])
        labels1 = torch.argmax(labels1, dim=1)
        
        #print('labels1[0]',labels1[0])
        labels1 = labels1.contiguous().view(-1, 1)
        #labels2 = torch.argmax(labels2, dim=1)
        labels2 = labels2.contiguous().view(-1, 1)

        print('labels1\n',labels1)
        print('labels2\n',labels2)
        #print('label1 shape0:',labels1.shape[0],'label2 shape0:',labels2.shape[0],'feature1 shape0:',features1.shape[0],'feature2 shape0:',features2.shape[0])
        if labels1.shape[0] != batch_size:
            raise ValueError('Num of labels does not match num of features')
        mask = torch.eq(labels1, labels2.T).float().to(device)
        mask2 = torch.eq(labels2, labels2.T).float().to(device)
        #mask3  based on worstk
        mask3 = torch.zeros(batch_size)
        #mask4  1 for mask and 0 for mask3, designed for samples not in worstk classes
        mask4 = torch.zeros(batch_size)
        for i in range(batch_size):
            #print('labels2[i]',labels2[i],'worstk',worstk)
            if labels2[i] in worstk:
                mask3[i] = 1
        mask3 = mask3.to(device)  
             
        mask4 = 1.-mask3
        
        mask4 = mask4.to(device)
        print('mask\n',mask)
        print('mask2\n',mask2)
        print('mask3\n',mask3)
        print('mask4\n',mask4)
        #40print('mask3',mask3)
        # compute logits
        anchor_dot_contrast1 = torch.div(                
            torch.matmul(features1, features2.T),
            self.temperature)  # Lx * Lu
        anchor_dot_contrast2 = torch.div(
            torch.matmul(features2, features2.T),
            self.temperature)  # Lu * Lu
        anchor_dot_contrast3 = torch.div(
            torch.matmul(features2, features2.T)+self.distance,   #0.5 是distance, 可以考虑成类间距离或者类和最远样本的距离
            self.temperature)  # Lu * Lu
        
        print('anchor_dot_contrast1\n',anchor_dot_contrast1)
        print('anchor_dot_contrast2\n',anchor_dot_contrast2)
        print('anchor_dot_contrast3\n',anchor_dot_contrast3)

        # for numerical stability
        logits_max1, _ = torch.max(anchor_dot_contrast1, dim=1, keepdim=True)
        logits_max2, _ = torch.max(anchor_dot_contrast2, dim=1, keepdim=True)
        logits_max3, _ = torch.max(anchor_dot_contrast3, dim=1, keepdim=True)
        logits1 = anchor_dot_contrast1 - logits_max1.detach()
        logits2 = anchor_dot_contrast2 - logits_max2.detach()
        #logits3 = anchor_dot_contrast3 - logits_max3.detach()
        logits3 = anchor_dot_contrast3 - logits_max2.detach()  #上下两行到底用哪个 可以都试试
        exp_logits1 = torch.exp(logits1)
        exp_logits2 = torch.exp(logits2)
        exp_logits3 = torch.exp(logits3)

        print('exp_logits1\n',exp_logits1)
        print('exp_logits2\n',exp_logits2)
        print('exp_logits3\n',exp_logits3)
      
        # 构建mask 
        #logits_mask = torch.ones_like(mask) - torch.eye(batch_size)     
        logits_mask1 = torch.ones_like(mask).to(device)                          #label and unlabel
        

        logits_mask2 = torch.ones_like(mask2).to(device) - torch.eye(batch_size2).to(device)  #unlabel and unlabel

        positives_mask1 = mask * logits_mask1
        negatives_mask1 = 1. - mask                 #? 这里是不是有问题？ 是 1-mask 还是 1-positive mask? 
        #??????????????????????????????????????????????????????????????????????????????????????????????
        positives_mask2 = mask2 * logits_mask2
        negatives_mask2 = 1. - mask2
          
        num_positives_per_row  = torch.sum(positives_mask1 , axis=1) # 除了自己之外，正样本的个数  [2 0 2 2]    
        num_positives_per_row_selected = mask3 * num_positives_per_row.t() 
        num_positives_per_row_unselected = mask4 * num_positives_per_row.t() 

        num_positives_per_row2  = torch.sum(positives_mask2 , axis=1) # 除了自己之外，正样本的个数  [2 0 2 2]    
        num_positives_per_row_selected2 = mask3 * num_positives_per_row.t() 
        num_positives_per_row_unselected2 = mask4 * num_positives_per_row.t() 

        print('logits_mask1\n',logits_mask1)
        print('logits_mask2\n',logits_mask2)
        print('positives_mask1\n',positives_mask1)
        print('negatives_mask1\n',negatives_mask1)
        print('positives_mask2\n',positives_mask2)
        print('negatives_mask2\n',negatives_mask2)
        print('num_positives_per_row\n',num_positives_per_row)
        print('num_positives_per_row_selected\n',num_positives_per_row_selected)
        print('num_positives_per_row_unselected\n',num_positives_per_row_unselected)

        #print('Number of elements greater than 0 for original selection:',(num_positives_per_row > 0).sum().item())
        #print('Number of elements greater than 0 for  my  selection:',(num_positives_per_row_selected > 0).sum().item())
        
        denominator = torch.sum(
        exp_logits2 * negatives_mask2, axis=1, keepdims=True) + torch.sum(
            exp_logits2 * positives_mask2, axis=1, keepdims=True)  
        
        denominator1 = torch.sum(
        exp_logits3 * negatives_mask2, axis=1, keepdims=True) + torch.sum(
            exp_logits3 * positives_mask2, axis=1, keepdims=True)  
        
        log_probs = logits1 - torch.log(denominator)
        if torch.any(torch.isnan(log_probs)):
            raise ValueError("Log_prob has nan!")
        
        log_probs1 = logits1 - torch.log(denominator1)
        if torch.any(torch.isnan(log_probs)):
            raise ValueError("Log_prob has nan!")
        print('shape!!!!!!!!!!!!!!!!!!')
        print(logits1.shape)
        print(denominator.shape)
        print(log_probs.shape)
        print('denominator\n',denominator)
        print('denominator1\n',denominator1)
        print('log_probs\n',log_probs)
        print('log_probs1\n',log_probs1)

        #log_probs = torch.sum(
        #    log_probs*positives_mask1 , axis=1)[num_positives_per_row > 0] / num_positives_per_row[num_positives_per_row > 0]
        log_probs = torch.sum(
            log_probs*positives_mask1 , axis=1)[num_positives_per_row_selected > 0] / num_positives_per_row_selected[num_positives_per_row_selected > 0]
        
        log_probs1 = torch.sum(
            log_probs1*positives_mask1 , axis=1)[num_positives_per_row_unselected > 0] / num_positives_per_row_unselected[num_positives_per_row_unselected > 0]
        
        print('log_probs_\n',log_probs)
        print('log_probs1_\n',log_probs1)
        # loss
        loss = -log_probs
        loss1 = -log_probs1
        print('loss\n',loss)
        print('loss1\n',loss1)
        #if self.scale_by_temperature:
        #    loss *= self.temperature
        loss = loss.mean()
        loss1 = loss1.mean()
        print('loss\n',loss)
        print('loss1\n',loss1)
        return loss+loss1

In [11]:
batch_size = 64
num_features = 5
features1 = torch.randn(batch_size, num_features).cuda()
features2 = torch.randn(batch_size, num_features).cuda()
labels1 = torch.randint(0, 3, (batch_size, num_features)).cuda()
labels2 = torch.randint(0, 3, (batch_size,)).cuda()
worstk = [0, 1]
tmask = None

loss_function = SupConLoss3()
loss = loss_function(tmask, worstk, features1, features2, labels1, labels2)
print(loss)

features1
 tensor([[-1.3319e+00, -2.9859e-01,  1.3565e+00, -2.2746e-02,  1.0880e+00],
        [ 9.7534e-01, -1.2635e+00, -2.1612e+00,  8.4856e-01, -6.1491e-01],
        [ 3.0849e-01,  1.1111e+00, -8.9221e-02,  3.7861e-01, -4.7281e-01],
        [ 1.7549e+00, -6.0274e-01, -3.9193e-01, -1.8942e-01, -7.0016e-02],
        [-1.3926e+00, -5.4271e-02,  1.0732e+00,  1.8287e+00, -9.0819e-01],
        [-4.7142e-01,  1.5794e+00, -6.0579e-01,  3.4573e-01,  2.3442e-01],
        [-8.2301e-01, -3.6539e-01, -6.0663e-01, -9.3901e-01, -5.5511e-01],
        [-5.4449e-01, -4.4430e-01,  4.7565e-02, -7.8211e-01, -9.9691e-01],
        [-6.2123e-01, -1.3961e-01,  7.2223e-01, -6.3786e-01, -1.2132e+00],
        [ 5.4021e-01, -1.1646e+00,  5.0959e-01, -1.1803e+00, -8.0963e-01],
        [-6.6417e-01, -6.1459e-01, -6.2437e-01,  2.5477e-01, -1.2060e-01],
        [-9.4313e-01,  1.4213e-01,  7.0065e-01, -8.4266e-01,  8.6579e-01],
        [ 1.1423e+00, -1.3140e+00,  2.0399e+00,  3.5004e-01, -2.1559e+00],
        [-5.89

In [8]:
batch_size = 5
num_features = 3

# 随机生成一个形状为 (batch_size, batch_size) 的整数张量，范围在 [0, 1]
positives_mask1 = torch.randint(0, 2, (batch_size, batch_size))

print("positives_mask1:", positives_mask1)

num_positives_per_row = torch.sum(positives_mask1, axis=1)

print("num_positives_per_row:", num_positives_per_row)

positives_mask1: tensor([[1, 1, 1, 0, 1],
        [1, 0, 0, 0, 1],
        [1, 0, 1, 0, 0],
        [1, 1, 0, 1, 0],
        [1, 1, 0, 0, 0]])
num_positives_per_row: tensor([4, 2, 2, 3, 2])


In [5]:
class SupConLoss(nn.Module):
   
    def __init__(self, temperature=0.07, contrast_mode='all',
                 base_temperature=0.07):
        super(SupConLoss, self).__init__()
        self.temperature = temperature
        self.contrast_mode = contrast_mode
        self.base_temperature = base_temperature

    def forward(self, features, labels=None, mask=None):
     
        device = (torch.device('cuda')
                  if features.is_cuda
                  else torch.device('cpu'))

        if len(features.shape) < 3:
            raise ValueError('`features` needs to be [bsz, n_views, ...],'
                             'at least 3 dimensions are required')
        if len(features.shape) > 3:
            features = features.view(features.shape[0], features.shape[1], -1)

        batch_size = features.shape[0]
        if labels is not None and mask is not None:
            raise ValueError('Cannot define both `labels` and `mask`')
        elif labels is None and mask is None:
            mask = torch.eye(batch_size, dtype=torch.float32).to(device)
        elif labels is not None:
            labels = labels.contiguous().view(-1, 1)
            if labels.shape[0] != batch_size:
                raise ValueError('Num of labels does not match num of features')
            mask = torch.eq(labels, labels.T).float().to(device)
        else:
            mask = mask.float().to(device)
        print('labels\n',labels)
        print('mask!!!!!!\n',mask)
        contrast_count = features.shape[1]
        contrast_feature = torch.cat(torch.unbind(features, dim=1), dim=0)
        if self.contrast_mode == 'one':
            anchor_feature = features[:, 0]
            anchor_count = 1
        elif self.contrast_mode == 'all':
            anchor_feature = contrast_feature
            anchor_count = contrast_count
        else:
            raise ValueError('Unknown mode: {}'.format(self.contrast_mode))

        # compute logits
        anchor_dot_contrast = torch.div(
            torch.matmul(anchor_feature, contrast_feature.T),
            self.temperature)
        # for numerical stability
        logits_max, _ = torch.max(anchor_dot_contrast, dim=1, keepdim=True)
        logits = anchor_dot_contrast - logits_max.detach()
        print('anchor_dot_contrast.shape\n',anchor_dot_contrast.shape)
        print('logits_max.shape\n',logits_max.shape)
        print('logits.shape\n',logits.shape)
        # tile mask
        mask = mask.repeat(anchor_count, contrast_count)
        # mask-out self-contrast cases
        logits_mask = torch.scatter(
            torch.ones_like(mask),
            1,
            torch.arange(batch_size * anchor_count).view(-1, 1).to(device),
            0
        )
        mask = mask * logits_mask

        # compute log_prob
        exp_logits = torch.exp(logits) * logits_mask
        log_prob = logits - torch.log(exp_logits.sum(1, keepdim=True))
        print('logits shape\n',logits.shape)
        print('exp_logits.shape\n',exp_logits.shape)
        print('log_prob.shape\n',log_prob.shape)

        # compute mean of log-likelihood over positive
        # modified to handle edge cases when there is no positive pair
        # for an anchor point. 
        # Edge case e.g.:- 
        # features of shape: [4,1,...]
        # labels:            [0,1,1,2]
        # loss before mean:  [nan, ..., ..., nan] 
        #mask_pos_pairs = mask.sum(1)
        #mask_pos_pairs = torch.where(mask_pos_pairs < 1e-6, 1, mask_pos_pairs)
        #mask_pos_pairs = mask.sum(1)
        mask_pos_pairs = mask.sum(1)
        mask_pos_pairs = mask_pos_pairs.type(torch.LongTensor)
        mask_pos_pairs = torch.where(mask_pos_pairs < 0, 1, mask_pos_pairs)
        mask_pos_pairs = mask_pos_pairs.to(device)
        mean_log_prob_pos = (mask * log_prob).sum(1) / mask_pos_pairs
        #mask_pos_pairs = torch.where(mask_pos_pairs < torch.tensor(1e-6, dtype=mask_pos_pairs.dtype), 1, mask_pos_pairs)
        mean_log_prob_pos = (mask * log_prob).sum(1) / mask_pos_pairs

        # loss
        loss = - (self.temperature / self.base_temperature) * mean_log_prob_pos
        loss = loss.view(anchor_count, batch_size).mean()

        return loss

In [6]:
import torch
import torch.nn as nn

# 创建随机特征向量和标签
batch_size = 4
n_views = 2
num_features = 3
features = torch.randn(batch_size, n_views, num_features).cuda()
labels = torch.randint(0, 3, (batch_size,)).cuda()

# 创建损失函数实例
loss_function = SupConLoss().cuda()

# 计算损失
loss = loss_function(features, labels)
print(loss)

labels
 tensor([[0],
        [0],
        [1],
        [2]], device='cuda:0')
mask!!!!!!
 tensor([[1., 1., 0., 0.],
        [1., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]], device='cuda:0')
anchor_dot_contrast.shape
 torch.Size([8, 8])
logits_max.shape
 torch.Size([8, 1])
logits.shape
 torch.Size([8, 8])
logits shape
 torch.Size([8, 8])
exp_logits.shape
 torch.Size([8, 8])
log_prob.shape
 torch.Size([8, 8])
tensor(10.9031, device='cuda:0')
